name: standard
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  standard:
    uses: bounded-systems/.github/.github/workflows/repo-standard.yml@63fb16d135258a3acfbfe4ceb4db5c2a17f7dc1f
    with:
      security: true
      test: true
      runtime: nix
      test-command: "nix shell nixpkgs#bun -c bun test"
